### PR TITLE
Use system LUA lib instead a local copy

### PR DESCRIPTION
**Pull request by eliasrm87**
Avoid necessity of maintaining a local copy of the LUA lib.

### CODE REVIEW

**Comment by kaaashy** [comment]
Thanks! Are you sure this is the fork you want to contribute to, and not https://github.com/EssGeeEich/LuaEditor? This is a slightly modified fork which I've extended so I can load and autocomplete some predefined functions which are available in Avorion, a game I'm working on.

**Comment by eliasrm87** [comment]
Welcome! You are correct, I should also send this pull request to EssGeeEich/LuaEditor. The reason I have sent it to you instead is that, even having your specific additions, you have improved it, it is more useful for me and the original one seems to be unattended for a year.

Regards

**Comment by kaaashy** [comment]
Welp, sorry it took me so long; totally forgot about this. I added some more changes so function hinting is now possible, you should check it out :)

**Comment by eliasrm87** [comment]
Thank you very much. I'll check that.

Regards

**Pull request merged**
